### ISSUE TITLE
Implement dashboard header pay and request buttons

### ISSUE THREAD

**Issue by andresousa** [pokettocash/poketto-ios#22]

**Comment by andresousa** [comment]
Link to [#8](https://github.com/pokettocash/poketto-ios/issues/8)

**Comment by andresousa** [comment]
- [ ] Collection view divided by week days [#24](https://github.com/pokettocash/poketto-ios/issues/24)
- [ ] Display transaction value rounded to xDai unit [#29](https://github.com/pokettocash/poketto-ios/issues/24)
- [ ] Display address or contact full name for each transaction [#30](https://github.com/pokettocash/poketto-ios/issues/30)
